dist: xenial   # required for Python >= 3.7
language: python
# command to install dependencies
python:
  - "3.7"
install:
  - pip install -r requirements-build.txt 
# command to run tests
script:
  - python manage.py collectstatic
  - python manage.py makemigrations
  - python manage.py migrate 
  - python manage.py test