# Generated by Django 2.2 on 2019-05-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='embed_video_url',
            field=models.CharField(default='', editable=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(default='', max_length=2000, verbose_name='video link'),
        ),
    ]
