# Generated by Django 2.2 on 2019-05-22 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("lessons", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(allow_unicode=True, default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="embed_video_url",
            field=models.CharField(default="", editable=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(allow_unicode=True, default=uuid.uuid1, unique=True),
        ),
    ]
