# Generated by Django 2.2 on 2019-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lessons", "0009_auto_20190609_1439")]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="activate_description",
            field=models.TextField(
                blank=True, default="", verbose_name="activate description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="activate_description2",
            field=models.TextField(
                blank=True, default="", verbose_name="activate description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="activate_description3",
            field=models.TextField(
                blank=True, default="", verbose_name="activate description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="controlled_practice_description",
            field=models.TextField(
                blank=True, default="", verbose_name="controlled practice description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="engage_description",
            field=models.TextField(
                blank=True, default="", verbose_name="engage description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="engage_description2",
            field=models.TextField(
                blank=True, default="", verbose_name="engage description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="review_description",
            field=models.TextField(
                blank=True, default="", verbose_name="review description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="study_description",
            field=models.TextField(
                blank=True, default="", verbose_name="study description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="study_description2",
            field=models.TextField(
                blank=True, default="", verbose_name="study description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="wrap_up_description",
            field=models.TextField(
                blank=True, default="", verbose_name="wrap up description"
            ),
        ),
        migrations.AlterUniqueTogether(name="lesson", unique_together=set()),
    ]
