# Generated by Django 2.2 on 2019-06-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_auto_20190609_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='controlled_practice_description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='controlled_practice_time',
        ),
    ]
